create table ban_an (ma_ban_an bigint not null auto_increment, ghi_chu varchar(255), suc_chua integer not null, tinh_trang varchar(255) not null, primary key (ma_ban_an)) engine=InnoDB;
create table chi_tiet_goi_mon (ma_mon_an bigint not null, ma_order bigint not null, so_luong_mon_an integer, chi_tiet_goi_mon_mon_an_foreign_key bigint not null, chi_tiet_goi_mon_phieu_goi_mon_foreign_key bigint not null, primary key (ma_mon_an, ma_order)) engine=InnoDB;
create table chi_tiet_phieu_nhap (ma_nguyen_vat_lieu bigint not null, ma_phieu_nhap bigint not null, so_luong_nhap integer, chi_tiet_phieu_nhap_nguyen_vat_lieu_foreign_key bigint not null, chi_tiet_phieu_nhap_phieu_nhap_foreign_key bigint not null, primary key (ma_nguyen_vat_lieu, ma_phieu_nhap)) engine=InnoDB;
create table hoa_don (ma_hoa_don bigint not null auto_increment, chiet_khau double precision, thoi_gian_thanh_toan datetime(6) not null, tinh_trang integer not null, tong_tien double precision not null, hoa_don_hoi_vien_foreign_key bigint, hoa_don_khach_hang_foreign_key bigint, hoa_don_nhan_vien_foreign_key bigint, hoa_don_phieu_goi_mon_foreign_key bigint, primary key (ma_hoa_don)) engine=InnoDB;
create table hoi_vien (ma_hoi_vien bigint not null auto_increment, dia_chi varchar(255), email varchar(255) not null, mat_khau varchar(255) not null, quyen_loi varchar(255), so_dien_thoai varchar(255) not null, ten_hoi_vien varchar(255) not null, tong_so_tien_thanh_toan double precision, primary key (ma_hoi_vien)) engine=InnoDB;
create table khach_hang (ma_khach_hang bigint not null auto_increment, dia_chi varchar(255) not null, email varchar(255) not null, so_dien_thoai varchar(255) not null, ten_khach_hang varchar(255) not null, primary key (ma_khach_hang)) engine=InnoDB;
create table lich_hen (ma_lich_hen bigint not null auto_increment, ngay_hen date, nhu_cau varchar(255), so_luong_khach integer, thoi_gian datetime(6), tinh_trang integer, lich_hen_ban_an_foreign_key bigint, lich_hen_khach_hang_foreign_key bigint not null, lich_hen_nhan_vien_foreign_key bigint, primary key (ma_lich_hen)) engine=InnoDB;
create table mon_an (ma_mon_an bigint not null auto_increment, don_gia double precision, don_vi varchar(255), hinh_anh varchar(255), mo_ta varchar(255), mo_ta_ngan varchar(255), ten_mon_an varchar(255), mon_an_nhom_mon_an_foreign_key bigint not null, primary key (ma_mon_an)) engine=InnoDB;
create table nguyen_vat_lieu (ma_nguyen_vat_lieu bigint not null auto_increment, don_gia double precision, don_vi varchar(255), so_luong_ton_kho integer, ten_nguyen_vat_lieu varchar(255), tinh_trang varchar(255), primary key (ma_nguyen_vat_lieu)) engine=InnoDB;
create table nha_cung_cap (ma_nha_cung_cap bigint not null auto_increment, dia_chi varchar(255), mo_ta_nha_cung_cap varchar(255), so_dien_thoai varchar(255) not null, ten_nha_cung_cap varchar(255), primary key (ma_nha_cung_cap)) engine=InnoDB;
create table nhan_vien (ma_nhan_vien bigint not null auto_increment, email varchar(255), anh_dai_dien varchar(255), chuc_vu varchar(255), dia_chi varchar(255), luong double precision, so_dien_thoai varchar(255), ten_nhan_vien varchar(255), nhan_vien_tai_khoan_forgein_key bigint, primary key (ma_nhan_vien)) engine=InnoDB;
create table nhom_mon_an (ma_nhom bigint not null auto_increment, mo_ta varchar(255), ten_nhom varchar(255), primary key (ma_nhom)) engine=InnoDB;
create table phieu_goi_mon (ma_order bigint not null auto_increment, ghi_chu_mon_an varchar(255), phieu_goi_mon_ban_an_foreign_key bigint not null, phieu_goi_mon_nhan_vien_foreign_key bigint not null, primary key (ma_order)) engine=InnoDB;
create table phieu_nhap (ma_phieu_nhap bigint not null auto_increment, ghi_chu varchar(255), ngay_nhap_hang datetime(6), tong_gia_nhap double precision, phieu_nhap_nha_cung_cap_foreign_key bigint not null, phieu_nhap_nhan_vien_foreign_key bigint not null, primary key (ma_phieu_nhap)) engine=InnoDB;
create table taikhoan (ma_tai_khoan bigint not null auto_increment, mat_khau varchar(255) not null, ten_tai_khoan varchar(255), primary key (ma_tai_khoan)) engine=InnoDB;
alter table hoi_vien add constraint UK_csook5xnk32xw1bokdpox0wdb unique (email);
alter table nha_cung_cap add constraint UK_cuf78wlhewgijvkdhpyo1woi5 unique (so_dien_thoai);
alter table nhan_vien add constraint UK_12waxxsiniyddv2lt9ianfh8a unique (email);
alter table taikhoan add constraint UK_pn69efomb5xfas83ph3m73425 unique (ten_tai_khoan);
alter table chi_tiet_goi_mon add constraint FKeu5wgck2psgr77w3fy974sgcj foreign key (chi_tiet_goi_mon_mon_an_foreign_key) references mon_an (ma_mon_an);
alter table chi_tiet_goi_mon add constraint FKiwdnsh8umb13utgwnh3iolk43 foreign key (chi_tiet_goi_mon_phieu_goi_mon_foreign_key) references phieu_goi_mon (ma_order);
alter table chi_tiet_phieu_nhap add constraint FKt9ierohgo7p5i8bjjw6wi3jlh foreign key (chi_tiet_phieu_nhap_nguyen_vat_lieu_foreign_key) references nguyen_vat_lieu (ma_nguyen_vat_lieu);
alter table chi_tiet_phieu_nhap add constraint FK9reox427sx0pctkrnaqc3e9v1 foreign key (chi_tiet_phieu_nhap_phieu_nhap_foreign_key) references phieu_nhap (ma_phieu_nhap);
alter table hoa_don add constraint FKkj71losh6g82surdsuq4hvwbe foreign key (hoa_don_hoi_vien_foreign_key) references hoi_vien (ma_hoi_vien);
alter table hoa_don add constraint FKdjptraaljhen8wta139df905i foreign key (hoa_don_khach_hang_foreign_key) references khach_hang (ma_khach_hang);
alter table hoa_don add constraint FKtdrxkdky5udarvnab0bpob2om foreign key (hoa_don_nhan_vien_foreign_key) references nhan_vien (ma_nhan_vien);
alter table hoa_don add constraint FKdrhfku88af7h53ceom786sk7a foreign key (hoa_don_phieu_goi_mon_foreign_key) references phieu_goi_mon (ma_order);
alter table lich_hen add constraint FKiyed67v05cuosqg6rulawyqk3 foreign key (lich_hen_ban_an_foreign_key) references ban_an (ma_ban_an);
alter table lich_hen add constraint FKsha0hjrgt2djgsnqp34k6nphc foreign key (lich_hen_khach_hang_foreign_key) references khach_hang (ma_khach_hang);
alter table lich_hen add constraint FKi2rwgpki1rq3n7xpaygrl5qn7 foreign key (lich_hen_nhan_vien_foreign_key) references nhan_vien (ma_nhan_vien);
alter table mon_an add constraint FKmf0kjtq5ugc1ps7e08rjvaq3n foreign key (mon_an_nhom_mon_an_foreign_key) references nhom_mon_an (ma_nhom);
alter table nhan_vien add constraint FKmsg6em0vf83n4ymqlg65qcu83 foreign key (nhan_vien_tai_khoan_forgein_key) references taikhoan (ma_tai_khoan);
alter table phieu_goi_mon add constraint FKgo2b1hq7d3xn97drkuxi6g6mr foreign key (phieu_goi_mon_ban_an_foreign_key) references ban_an (ma_ban_an);
alter table phieu_goi_mon add constraint FKfkcxq772ghp2j9ghmgty3d4k foreign key (phieu_goi_mon_nhan_vien_foreign_key) references nhan_vien (ma_nhan_vien);
alter table phieu_nhap add constraint FKeka7cj4vbauopbxtu5eqk4bwr foreign key (phieu_nhap_nha_cung_cap_foreign_key) references nha_cung_cap (ma_nha_cung_cap);
alter table phieu_nhap add constraint FKkcney1svi8wveoh66fcemv1i3 foreign key (phieu_nhap_nhan_vien_foreign_key) references nhan_vien (ma_nhan_vien);
create table ban_an (ma_ban_an bigint not null auto_increment, ghi_chu varchar(255), suc_chua integer not null, tinh_trang varchar(255) not null, primary key (ma_ban_an)) engine=InnoDB;
create table chi_tiet_goi_mon (ma_mon_an bigint not null, ma_order bigint not null, so_luong_mon_an integer, chi_tiet_goi_mon_mon_an_foreign_key bigint not null, chi_tiet_goi_mon_phieu_goi_mon_foreign_key bigint not null, primary key (ma_mon_an, ma_order)) engine=InnoDB;
create table chi_tiet_phieu_nhap (ma_nguyen_vat_lieu bigint not null, ma_phieu_nhap bigint not null, so_luong_nhap integer, chi_tiet_phieu_nhap_nguyen_vat_lieu_foreign_key bigint not null, chi_tiet_phieu_nhap_phieu_nhap_foreign_key bigint not null, primary key (ma_nguyen_vat_lieu, ma_phieu_nhap)) engine=InnoDB;
create table hoa_don (ma_hoa_don bigint not null auto_increment, chiet_khau double precision, thoi_gian_thanh_toan datetime(6) not null, tinh_trang integer not null, tong_tien double precision not null, hoa_don_hoi_vien_foreign_key bigint, hoa_don_khach_hang_foreign_key bigint, hoa_don_nhan_vien_foreign_key bigint, hoa_don_phieu_goi_mon_foreign_key bigint, primary key (ma_hoa_don)) engine=InnoDB;
create table hoi_vien (ma_hoi_vien bigint not null auto_increment, dia_chi varchar(255), email varchar(255) not null, mat_khau varchar(255) not null, quyen_loi varchar(255), so_dien_thoai varchar(255) not null, ten_hoi_vien varchar(255) not null, tong_so_tien_thanh_toan double precision, primary key (ma_hoi_vien)) engine=InnoDB;
create table khach_hang (ma_khach_hang bigint not null auto_increment, dia_chi varchar(255) not null, email varchar(255) not null, so_dien_thoai varchar(255) not null, ten_khach_hang varchar(255) not null, primary key (ma_khach_hang)) engine=InnoDB;
create table lich_hen (ma_lich_hen bigint not null auto_increment, ngay_hen date, nhu_cau varchar(255), so_luong_khach integer, thoi_gian datetime(6), tinh_trang integer, lich_hen_ban_an_foreign_key bigint, lich_hen_khach_hang_foreign_key bigint not null, lich_hen_nhan_vien_foreign_key bigint, primary key (ma_lich_hen)) engine=InnoDB;
create table mon_an (ma_mon_an bigint not null auto_increment, don_gia double precision, don_vi varchar(255), hinh_anh varchar(255), mo_ta varchar(255), mo_ta_ngan varchar(255), ten_mon_an varchar(255), mon_an_nhom_mon_an_foreign_key bigint not null, primary key (ma_mon_an)) engine=InnoDB;
create table nguyen_vat_lieu (ma_nguyen_vat_lieu bigint not null auto_increment, don_gia double precision, don_vi varchar(255), so_luong_ton_kho integer, ten_nguyen_vat_lieu varchar(255), tinh_trang varchar(255), primary key (ma_nguyen_vat_lieu)) engine=InnoDB;
create table nha_cung_cap (ma_nha_cung_cap bigint not null auto_increment, dia_chi varchar(255), mo_ta_nha_cung_cap varchar(255), so_dien_thoai varchar(255) not null, ten_nha_cung_cap varchar(255), primary key (ma_nha_cung_cap)) engine=InnoDB;
create table nhan_vien (ma_nhan_vien bigint not null auto_increment, email varchar(255), anh_dai_dien varchar(255), chuc_vu varchar(255), dia_chi varchar(255), luong double precision, so_dien_thoai varchar(255), ten_nhan_vien varchar(255), nhan_vien_tai_khoan_forgein_key bigint, primary key (ma_nhan_vien)) engine=InnoDB;
create table nhom_mon_an (ma_nhom bigint not null auto_increment, mo_ta varchar(255), ten_nhom varchar(255), primary key (ma_nhom)) engine=InnoDB;
create table phieu_goi_mon (ma_order bigint not null auto_increment, ghi_chu_mon_an varchar(255), phieu_goi_mon_ban_an_foreign_key bigint not null, phieu_goi_mon_nhan_vien_foreign_key bigint not null, primary key (ma_order)) engine=InnoDB;
create table phieu_nhap (ma_phieu_nhap bigint not null auto_increment, ghi_chu varchar(255), ngay_nhap_hang datetime(6), tong_gia_nhap double precision, phieu_nhap_nha_cung_cap_foreign_key bigint not null, phieu_nhap_nhan_vien_foreign_key bigint not null, primary key (ma_phieu_nhap)) engine=InnoDB;
create table taikhoan (ma_tai_khoan bigint not null auto_increment, mat_khau varchar(255) not null, ten_tai_khoan varchar(255), primary key (ma_tai_khoan)) engine=InnoDB;
alter table hoi_vien add constraint UK_csook5xnk32xw1bokdpox0wdb unique (email);
alter table nha_cung_cap add constraint UK_cuf78wlhewgijvkdhpyo1woi5 unique (so_dien_thoai);
alter table nhan_vien add constraint UK_12waxxsiniyddv2lt9ianfh8a unique (email);
alter table taikhoan add constraint UK_pn69efomb5xfas83ph3m73425 unique (ten_tai_khoan);
alter table chi_tiet_goi_mon add constraint FKeu5wgck2psgr77w3fy974sgcj foreign key (chi_tiet_goi_mon_mon_an_foreign_key) references mon_an (ma_mon_an);
alter table chi_tiet_goi_mon add constraint FKiwdnsh8umb13utgwnh3iolk43 foreign key (chi_tiet_goi_mon_phieu_goi_mon_foreign_key) references phieu_goi_mon (ma_order);
alter table chi_tiet_phieu_nhap add constraint FKt9ierohgo7p5i8bjjw6wi3jlh foreign key (chi_tiet_phieu_nhap_nguyen_vat_lieu_foreign_key) references nguyen_vat_lieu (ma_nguyen_vat_lieu);
alter table chi_tiet_phieu_nhap add constraint FK9reox427sx0pctkrnaqc3e9v1 foreign key (chi_tiet_phieu_nhap_phieu_nhap_foreign_key) references phieu_nhap (ma_phieu_nhap);
alter table hoa_don add constraint FKkj71losh6g82surdsuq4hvwbe foreign key (hoa_don_hoi_vien_foreign_key) references hoi_vien (ma_hoi_vien);
alter table hoa_don add constraint FKdjptraaljhen8wta139df905i foreign key (hoa_don_khach_hang_foreign_key) references khach_hang (ma_khach_hang);
alter table hoa_don add constraint FKtdrxkdky5udarvnab0bpob2om foreign key (hoa_don_nhan_vien_foreign_key) references nhan_vien (ma_nhan_vien);
alter table hoa_don add constraint FKdrhfku88af7h53ceom786sk7a foreign key (hoa_don_phieu_goi_mon_foreign_key) references phieu_goi_mon (ma_order);
alter table lich_hen add constraint FKiyed67v05cuosqg6rulawyqk3 foreign key (lich_hen_ban_an_foreign_key) references ban_an (ma_ban_an);
alter table lich_hen add constraint FKsha0hjrgt2djgsnqp34k6nphc foreign key (lich_hen_khach_hang_foreign_key) references khach_hang (ma_khach_hang);
alter table lich_hen add constraint FKi2rwgpki1rq3n7xpaygrl5qn7 foreign key (lich_hen_nhan_vien_foreign_key) references nhan_vien (ma_nhan_vien);
alter table mon_an add constraint FKmf0kjtq5ugc1ps7e08rjvaq3n foreign key (mon_an_nhom_mon_an_foreign_key) references nhom_mon_an (ma_nhom);
alter table nhan_vien add constraint FKmsg6em0vf83n4ymqlg65qcu83 foreign key (nhan_vien_tai_khoan_forgein_key) references taikhoan (ma_tai_khoan);
alter table phieu_goi_mon add constraint FKgo2b1hq7d3xn97drkuxi6g6mr foreign key (phieu_goi_mon_ban_an_foreign_key) references ban_an (ma_ban_an);
alter table phieu_goi_mon add constraint FKfkcxq772ghp2j9ghmgty3d4k foreign key (phieu_goi_mon_nhan_vien_foreign_key) references nhan_vien (ma_nhan_vien);
alter table phieu_nhap add constraint FKeka7cj4vbauopbxtu5eqk4bwr foreign key (phieu_nhap_nha_cung_cap_foreign_key) references nha_cung_cap (ma_nha_cung_cap);
alter table phieu_nhap add constraint FKkcney1svi8wveoh66fcemv1i3 foreign key (phieu_nhap_nhan_vien_foreign_key) references nhan_vien (ma_nhan_vien);
create table ban_an (ma_ban_an bigint not null auto_increment, ghi_chu varchar(255), suc_chua integer not null, tinh_trang varchar(255) not null, primary key (ma_ban_an)) engine=InnoDB;
create table chi_tiet_goi_mon (ma_mon_an bigint not null, ma_order bigint not null, so_luong_mon_an integer, chi_tiet_goi_mon_mon_an_foreign_key bigint not null, chi_tiet_goi_mon_phieu_goi_mon_foreign_key bigint not null, primary key (ma_mon_an, ma_order)) engine=InnoDB;
create table chi_tiet_phieu_nhap (ma_nguyen_vat_lieu bigint not null, ma_phieu_nhap bigint not null, so_luong_nhap integer, chi_tiet_phieu_nhap_nguyen_vat_lieu_foreign_key bigint not null, chi_tiet_phieu_nhap_phieu_nhap_foreign_key bigint not null, primary key (ma_nguyen_vat_lieu, ma_phieu_nhap)) engine=InnoDB;
create table hoa_don (ma_hoa_don bigint not null auto_increment, chiet_khau double precision, thoi_gian_thanh_toan datetime(6) not null, tinh_trang integer not null, tong_tien double precision not null, hoa_don_hoi_vien_foreign_key bigint, hoa_don_khach_hang_foreign_key bigint, hoa_don_nhan_vien_foreign_key bigint, hoa_don_phieu_goi_mon_foreign_key bigint, primary key (ma_hoa_don)) engine=InnoDB;
create table hoi_vien (ma_hoi_vien bigint not null auto_increment, dia_chi varchar(255), email varchar(255) not null, mat_khau varchar(255) not null, quyen_loi varchar(255), so_dien_thoai varchar(255) not null, ten_hoi_vien varchar(255) not null, tong_so_tien_thanh_toan double precision, primary key (ma_hoi_vien)) engine=InnoDB;
create table khach_hang (ma_khach_hang bigint not null auto_increment, dia_chi varchar(255) not null, email varchar(255) not null, so_dien_thoai varchar(255) not null, ten_khach_hang varchar(255) not null, primary key (ma_khach_hang)) engine=InnoDB;
create table lich_hen (ma_lich_hen bigint not null auto_increment, ngay_hen date, nhu_cau varchar(255), so_luong_khach integer, thoi_gian datetime(6), tinh_trang integer, lich_hen_ban_an_foreign_key bigint, lich_hen_khach_hang_foreign_key bigint not null, lich_hen_nhan_vien_foreign_key bigint, primary key (ma_lich_hen)) engine=InnoDB;
create table mon_an (ma_mon_an bigint not null auto_increment, don_gia double precision, don_vi varchar(255), hinh_anh varchar(255), mo_ta varchar(255), mo_ta_ngan varchar(255), ten_mon_an varchar(255), mon_an_nhom_mon_an_foreign_key bigint not null, primary key (ma_mon_an)) engine=InnoDB;
create table nguyen_vat_lieu (ma_nguyen_vat_lieu bigint not null auto_increment, don_gia double precision, don_vi varchar(255), so_luong_ton_kho integer, ten_nguyen_vat_lieu varchar(255), tinh_trang varchar(255), primary key (ma_nguyen_vat_lieu)) engine=InnoDB;
create table nha_cung_cap (ma_nha_cung_cap bigint not null auto_increment, dia_chi varchar(255), mo_ta_nha_cung_cap varchar(255), so_dien_thoai varchar(255) not null, ten_nha_cung_cap varchar(255), primary key (ma_nha_cung_cap)) engine=InnoDB;
create table nhan_vien (ma_nhan_vien bigint not null auto_increment, email varchar(255), anh_dai_dien varchar(255), chuc_vu varchar(255), dia_chi varchar(255), luong double precision, so_dien_thoai varchar(255), ten_nhan_vien varchar(255), nhan_vien_tai_khoan_forgein_key bigint, primary key (ma_nhan_vien)) engine=InnoDB;
create table nhom_mon_an (ma_nhom bigint not null auto_increment, mo_ta varchar(255), ten_nhom varchar(255), primary key (ma_nhom)) engine=InnoDB;
create table phieu_goi_mon (ma_order bigint not null auto_increment, ghi_chu_mon_an varchar(255), phieu_goi_mon_ban_an_foreign_key bigint not null, phieu_goi_mon_nhan_vien_foreign_key bigint not null, primary key (ma_order)) engine=InnoDB;
create table phieu_nhap (ma_phieu_nhap bigint not null auto_increment, ghi_chu varchar(255), ngay_nhap_hang datetime(6), tong_gia_nhap double precision, phieu_nhap_nha_cung_cap_foreign_key bigint not null, phieu_nhap_nhan_vien_foreign_key bigint not null, primary key (ma_phieu_nhap)) engine=InnoDB;
create table taikhoan (ma_tai_khoan bigint not null auto_increment, mat_khau varchar(255) not null, ten_tai_khoan varchar(255), primary key (ma_tai_khoan)) engine=InnoDB;
alter table hoi_vien add constraint UK_csook5xnk32xw1bokdpox0wdb unique (email);
alter table nha_cung_cap add constraint UK_cuf78wlhewgijvkdhpyo1woi5 unique (so_dien_thoai);
alter table nhan_vien add constraint UK_12waxxsiniyddv2lt9ianfh8a unique (email);
alter table taikhoan add constraint UK_pn69efomb5xfas83ph3m73425 unique (ten_tai_khoan);
alter table chi_tiet_goi_mon add constraint FKeu5wgck2psgr77w3fy974sgcj foreign key (chi_tiet_goi_mon_mon_an_foreign_key) references mon_an (ma_mon_an);
alter table chi_tiet_goi_mon add constraint FKiwdnsh8umb13utgwnh3iolk43 foreign key (chi_tiet_goi_mon_phieu_goi_mon_foreign_key) references phieu_goi_mon (ma_order);
alter table chi_tiet_phieu_nhap add constraint FKt9ierohgo7p5i8bjjw6wi3jlh foreign key (chi_tiet_phieu_nhap_nguyen_vat_lieu_foreign_key) references nguyen_vat_lieu (ma_nguyen_vat_lieu);
alter table chi_tiet_phieu_nhap add constraint FK9reox427sx0pctkrnaqc3e9v1 foreign key (chi_tiet_phieu_nhap_phieu_nhap_foreign_key) references phieu_nhap (ma_phieu_nhap);
alter table hoa_don add constraint FKkj71losh6g82surdsuq4hvwbe foreign key (hoa_don_hoi_vien_foreign_key) references hoi_vien (ma_hoi_vien);
alter table hoa_don add constraint FKdjptraaljhen8wta139df905i foreign key (hoa_don_khach_hang_foreign_key) references khach_hang (ma_khach_hang);
alter table hoa_don add constraint FKtdrxkdky5udarvnab0bpob2om foreign key (hoa_don_nhan_vien_foreign_key) references nhan_vien (ma_nhan_vien);
alter table hoa_don add constraint FKdrhfku88af7h53ceom786sk7a foreign key (hoa_don_phieu_goi_mon_foreign_key) references phieu_goi_mon (ma_order);
alter table lich_hen add constraint FKiyed67v05cuosqg6rulawyqk3 foreign key (lich_hen_ban_an_foreign_key) references ban_an (ma_ban_an);
alter table lich_hen add constraint FKsha0hjrgt2djgsnqp34k6nphc foreign key (lich_hen_khach_hang_foreign_key) references khach_hang (ma_khach_hang);
alter table lich_hen add constraint FKi2rwgpki1rq3n7xpaygrl5qn7 foreign key (lich_hen_nhan_vien_foreign_key) references nhan_vien (ma_nhan_vien);
alter table mon_an add constraint FKmf0kjtq5ugc1ps7e08rjvaq3n foreign key (mon_an_nhom_mon_an_foreign_key) references nhom_mon_an (ma_nhom);
alter table nhan_vien add constraint FKmsg6em0vf83n4ymqlg65qcu83 foreign key (nhan_vien_tai_khoan_forgein_key) references taikhoan (ma_tai_khoan);
alter table phieu_goi_mon add constraint FKgo2b1hq7d3xn97drkuxi6g6mr foreign key (phieu_goi_mon_ban_an_foreign_key) references ban_an (ma_ban_an);
alter table phieu_goi_mon add constraint FKfkcxq772ghp2j9ghmgty3d4k foreign key (phieu_goi_mon_nhan_vien_foreign_key) references nhan_vien (ma_nhan_vien);
alter table phieu_nhap add constraint FKeka7cj4vbauopbxtu5eqk4bwr foreign key (phieu_nhap_nha_cung_cap_foreign_key) references nha_cung_cap (ma_nha_cung_cap);
alter table phieu_nhap add constraint FKkcney1svi8wveoh66fcemv1i3 foreign key (phieu_nhap_nhan_vien_foreign_key) references nhan_vien (ma_nhan_vien);
create table ban_an (ma_ban_an bigint not null auto_increment, ghi_chu varchar(255), suc_chua integer not null, tinh_trang varchar(255) not null, primary key (ma_ban_an)) engine=InnoDB;
create table chi_tiet_goi_mon (ma_mon_an bigint not null, ma_order bigint not null, so_luong_mon_an integer, chi_tiet_goi_mon_mon_an_foreign_key bigint not null, chi_tiet_goi_mon_phieu_goi_mon_foreign_key bigint not null, primary key (ma_mon_an, ma_order)) engine=InnoDB;
create table chi_tiet_phieu_nhap (ma_nguyen_vat_lieu bigint not null, ma_phieu_nhap bigint not null, so_luong_nhap integer, chi_tiet_phieu_nhap_nguyen_vat_lieu_foreign_key bigint not null, chi_tiet_phieu_nhap_phieu_nhap_foreign_key bigint not null, primary key (ma_nguyen_vat_lieu, ma_phieu_nhap)) engine=InnoDB;
create table hoa_don (ma_hoa_don bigint not null auto_increment, chiet_khau double precision, thoi_gian_thanh_toan datetime(6) not null, tinh_trang integer not null, tong_tien double precision not null, hoa_don_hoi_vien_foreign_key bigint, hoa_don_khach_hang_foreign_key bigint, hoa_don_nhan_vien_foreign_key bigint, hoa_don_phieu_goi_mon_foreign_key bigint, primary key (ma_hoa_don)) engine=InnoDB;
create table hoi_vien (ma_hoi_vien bigint not null auto_increment, dia_chi varchar(255), email varchar(255) not null, mat_khau varchar(255) not null, quyen_loi varchar(255), so_dien_thoai varchar(255) not null, ten_hoi_vien varchar(255) not null, tong_so_tien_thanh_toan double precision, primary key (ma_hoi_vien)) engine=InnoDB;
create table khach_hang (ma_khach_hang bigint not null auto_increment, dia_chi varchar(255) not null, email varchar(255) not null, so_dien_thoai varchar(255) not null, ten_khach_hang varchar(255) not null, primary key (ma_khach_hang)) engine=InnoDB;
create table lich_hen (ma_lich_hen bigint not null auto_increment, ngay_hen date, nhu_cau varchar(255), so_luong_khach integer, thoi_gian datetime(6), tinh_trang integer, lich_hen_ban_an_foreign_key bigint, lich_hen_khach_hang_foreign_key bigint not null, lich_hen_nhan_vien_foreign_key bigint, primary key (ma_lich_hen)) engine=InnoDB;
create table mon_an (ma_mon_an bigint not null auto_increment, don_gia double precision, don_vi varchar(255), hinh_anh varchar(255), mo_ta varchar(255), mo_ta_ngan varchar(255), ten_mon_an varchar(255), mon_an_nhom_mon_an_foreign_key bigint not null, primary key (ma_mon_an)) engine=InnoDB;
create table nguyen_vat_lieu (ma_nguyen_vat_lieu bigint not null auto_increment, don_gia double precision, don_vi varchar(255), so_luong_ton_kho integer, ten_nguyen_vat_lieu varchar(255), tinh_trang varchar(255), primary key (ma_nguyen_vat_lieu)) engine=InnoDB;
create table nha_cung_cap (ma_nha_cung_cap bigint not null auto_increment, dia_chi varchar(255), mo_ta_nha_cung_cap varchar(255), so_dien_thoai varchar(255) not null, ten_nha_cung_cap varchar(255), primary key (ma_nha_cung_cap)) engine=InnoDB;
create table nhan_vien (ma_nhan_vien bigint not null auto_increment, email varchar(255), anh_dai_dien varchar(255), chuc_vu varchar(255), dia_chi varchar(255), luong double precision, so_dien_thoai varchar(255), ten_nhan_vien varchar(255), nhan_vien_tai_khoan_forgein_key bigint, primary key (ma_nhan_vien)) engine=InnoDB;
create table nhom_mon_an (ma_nhom bigint not null auto_increment, mo_ta varchar(255), ten_nhom varchar(255), primary key (ma_nhom)) engine=InnoDB;
create table phieu_goi_mon (ma_order bigint not null auto_increment, ghi_chu_mon_an varchar(255), phieu_goi_mon_ban_an_foreign_key bigint not null, phieu_goi_mon_nhan_vien_foreign_key bigint not null, primary key (ma_order)) engine=InnoDB;
create table phieu_nhap (ma_phieu_nhap bigint not null auto_increment, ghi_chu varchar(255), ngay_nhap_hang datetime(6), tong_gia_nhap double precision, phieu_nhap_nha_cung_cap_foreign_key bigint not null, phieu_nhap_nhan_vien_foreign_key bigint not null, primary key (ma_phieu_nhap)) engine=InnoDB;
create table taikhoan (ma_tai_khoan bigint not null auto_increment, mat_khau varchar(255) not null, ten_tai_khoan varchar(255), primary key (ma_tai_khoan)) engine=InnoDB;
alter table hoi_vien add constraint UK_csook5xnk32xw1bokdpox0wdb unique (email);
alter table nha_cung_cap add constraint UK_cuf78wlhewgijvkdhpyo1woi5 unique (so_dien_thoai);
alter table nhan_vien add constraint UK_12waxxsiniyddv2lt9ianfh8a unique (email);
alter table taikhoan add constraint UK_pn69efomb5xfas83ph3m73425 unique (ten_tai_khoan);
alter table chi_tiet_goi_mon add constraint FKeu5wgck2psgr77w3fy974sgcj foreign key (chi_tiet_goi_mon_mon_an_foreign_key) references mon_an (ma_mon_an);
alter table chi_tiet_goi_mon add constraint FKiwdnsh8umb13utgwnh3iolk43 foreign key (chi_tiet_goi_mon_phieu_goi_mon_foreign_key) references phieu_goi_mon (ma_order);
alter table chi_tiet_phieu_nhap add constraint FKt9ierohgo7p5i8bjjw6wi3jlh foreign key (chi_tiet_phieu_nhap_nguyen_vat_lieu_foreign_key) references nguyen_vat_lieu (ma_nguyen_vat_lieu);
alter table chi_tiet_phieu_nhap add constraint FK9reox427sx0pctkrnaqc3e9v1 foreign key (chi_tiet_phieu_nhap_phieu_nhap_foreign_key) references phieu_nhap (ma_phieu_nhap);
alter table hoa_don add constraint FKkj71losh6g82surdsuq4hvwbe foreign key (hoa_don_hoi_vien_foreign_key) references hoi_vien (ma_hoi_vien);
alter table hoa_don add constraint FKdjptraaljhen8wta139df905i foreign key (hoa_don_khach_hang_foreign_key) references khach_hang (ma_khach_hang);
alter table hoa_don add constraint FKtdrxkdky5udarvnab0bpob2om foreign key (hoa_don_nhan_vien_foreign_key) references nhan_vien (ma_nhan_vien);
alter table hoa_don add constraint FKdrhfku88af7h53ceom786sk7a foreign key (hoa_don_phieu_goi_mon_foreign_key) references phieu_goi_mon (ma_order);
alter table lich_hen add constraint FKiyed67v05cuosqg6rulawyqk3 foreign key (lich_hen_ban_an_foreign_key) references ban_an (ma_ban_an);
alter table lich_hen add constraint FKsha0hjrgt2djgsnqp34k6nphc foreign key (lich_hen_khach_hang_foreign_key) references khach_hang (ma_khach_hang);
alter table lich_hen add constraint FKi2rwgpki1rq3n7xpaygrl5qn7 foreign key (lich_hen_nhan_vien_foreign_key) references nhan_vien (ma_nhan_vien);
alter table mon_an add constraint FKmf0kjtq5ugc1ps7e08rjvaq3n foreign key (mon_an_nhom_mon_an_foreign_key) references nhom_mon_an (ma_nhom);
alter table nhan_vien add constraint FKmsg6em0vf83n4ymqlg65qcu83 foreign key (nhan_vien_tai_khoan_forgein_key) references taikhoan (ma_tai_khoan);
alter table phieu_goi_mon add constraint FKgo2b1hq7d3xn97drkuxi6g6mr foreign key (phieu_goi_mon_ban_an_foreign_key) references ban_an (ma_ban_an);
alter table phieu_goi_mon add constraint FKfkcxq772ghp2j9ghmgty3d4k foreign key (phieu_goi_mon_nhan_vien_foreign_key) references nhan_vien (ma_nhan_vien);
alter table phieu_nhap add constraint FKeka7cj4vbauopbxtu5eqk4bwr foreign key (phieu_nhap_nha_cung_cap_foreign_key) references nha_cung_cap (ma_nha_cung_cap);
alter table phieu_nhap add constraint FKkcney1svi8wveoh66fcemv1i3 foreign key (phieu_nhap_nhan_vien_foreign_key) references nhan_vien (ma_nhan_vien);
